apiVersion: apps/v1
kind: Deployment
metadata: 
  name: phpserve
  labels: 
    app: phpserve
spec: 
  selector: 
    matchLabels: 
      app: phpserve
  replicas: 2
  template: 
    metadata:      
      labels: 
        app: "phpserve"
    spec: 
      containers: 
        - name: phpserve
          image: "pelif/app-kubernetes-fullcycle:v3"    
          env: 
            - name: NAME
              value: "PELIF ELNIDA"
            - name: AGE
              value: "41"