apiVersion: apps/v1
kind: Deployment
metadata: 
  name: phpserve
  labels: 
    app: phpserve
spec: 
  selector: 
    matchLabels: 
      app: phpserve
  replicas: 2
  template: 
    metadata:      
      labels: 
        app: "phpserve"
    spec: 
      containers: 
        - name: phpserve
          image: "pelif/app-kubernetes-fullcycle:v4.6" 

          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 300m
              memory: 25Mi  

          startupProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 13  
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 5            
         
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2            
            timeoutSeconds: 5

          readinessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2            
            timeoutSeconds: 5

          envFrom: 
            - configMapRef:
                name: phpserve-env
            - secretRef:
                name: phpserve-secret

          # env: 
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: phpserve-env
          #         key: NAME 
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: phpserve-env
          #         key: AGE 