apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: phpserve-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: phpserve
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75