apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: phpserve
  labels: 
    app: phpserve
spec: 
  selector: 
    matchLabels: 
      app: phpserve
  replicas: 10
  template: 
    metadata:      
      labels: 
        app: "phpserve"
    spec: 
      containers: 
        - name: phpserve
          image: "pelif/app-kubernetes-fullcycle:v2"    
