apiVersion: v1 
kind: Service
metadata: 
  name: phpserve-service
spec: 
  selector: 
    app: phpserve
  type: ClusterIP
  ports:   
    - protocol: TCP
      port: 8001    
      targetPort: 80
    

