apiVersion: v1
kind: Service
metadata:
  name: phpserve-service
spec:
  selector:
    app: phpserve
  type: ClusterIP
  ports:
  - name: phpserve-service
    port: 80
    targetPort: 80
    protocol: TCP